### ISSUE TITLE
Can not reproduce result showed in origin paper

### ISSUE THREAD

**Issue by Watebear** [Junjie-Ye/ToolEyes#4]
Hello, I run your code and eval llama2-7b-chat model. The results is as follow:
![2024-02-22 11-00-14屏幕截图](https://github.com/Junjie-Ye/ToolEyes/assets/30264389/9e56111a-6374-45a0-b89a-eb5a494efb04)

it is much higher than your result in paper.
Could you please help me reproduce your result.

**Comment by GuanyuLi22** [comment]
@Watebear Could you please provide your detailed experiment settings? I also will check code.

**Comment by Junjie-Ye** [comment]
Hello, I'm pleased that you're intrigued by our work. We suspect that certain experimental variables such as prompts, temperature parameter, and tool feedback might have contributed to the inconsistency in the results. If possible, could you share the results you obtained through your inference for us to review? You can directly communicate with @GuanyuLi22, who is one of the authors of our study.

**Comment by Junjie-Ye** [comment]
I'm going to close this issue for now as it's taken too long to get a response, so feel free to contact us if you have any further questions about this.

**Comment by Junjie-Ye** [comment]
I'm going to close this issue for now as it's taken too long to get a response, so feel free to contact us if you have any further questions about this.
